### ISSUE TITLE
[Question] Cloudflare Workers Support

### ISSUE THREAD

**Issue by giacomolm** [lquixada/cross-fetch#82] opened 2020-12-28 13:31 UTC
Hi, 
I am testing - indirectly - the cross-fetch library on CloudFlare Workers and I get the following error:

'XMLHttpRequest is not defined'

Are you planning to support CF workers in the near future ? 

Please note that node-fetch seems to work with CF, but I couldn't find any "official" statement . 

TIA

**Comment by lquixada** [comment] 2020-12-28 16:44
Not familiar with CloudFlare Workers but the purpose of `cross-fetch` is just to act as a proxy for both `node-fetch` and `whatwg-fetch`. If the environment lacks the `XMLHttpRequest` object, maybe a polyfill for that could help you out.

**Comment by lquixada** [comment] 2020-12-28 16:47
I'm closing this as it seems a duplicate of #69 .

**Closed by lquixada** 2020-12-28 16:47 UTC
