### ISSUE TITLE
Cross-fetch is not usable in service workers

### ISSUE THREAD

**Issue by pimterry** [lquixada/cross-fetch#78] opened 2020-10-05 16:54 UTC
I'm using this library (via https://github.com/prisma-labs/graphql-request) and it fails to make requests when used within a browser service worker. More specifically, it throws:

```javascript
ReferenceError: XMLHttpRequest is not defined
    at browser-ponyfill.js:463
    at new Promise (<anonymous>)
    at Object.fetch [as default] (browser-ponyfill.js:455)
    at GraphQLClient.<anonymous> (index.ts:87)
    at step (createRequestBody.ts:45)
    at Object.next (createRequestBody.ts:45)
    at createRequestBody.ts:45
    at new Promise (<anonymous>)
    at createRequestBody.ts:45
    at GraphQLClient.request (index.ts:73)
```

Service workers do always have fetch available, but they _don't_ have XMLHttpRequest. See https://github.com/whatwg/xhr/issues/19 for some background from the spec discussion.

Because they are a browser environment though, https://github.com/lquixada/cross-fetch/blob/master/dist/browser-ponyfill.js from this library is used, which incorrectly seems to assume XHR is always available in all modern browser environments.

I think all that's required here is to fall back to the built-in Fetch that is available in this case.

**Comment by seaneking** [comment] 2020-10-16 08:37
I've also hit this issue, but in a different context — [Sapper](https://sapper.svelte.dev/) also has fetch available in its SSR environment but not XMLHttpRequest, and one of my dependencies (`prismic-javascript`) uses cross-fetch, making it unusable.

**Comment by abnemo** [comment] 2021-04-26 16:41
Hello guys!
I discovered a cool project called supabase. However, I wanted to use their javascript client supabase-js with deno, but XMLHttpRequest is not defined there too =(

**Comment by jcs224** [comment] 2021-05-11 01:16
Hopefully, this will be fixed now. A dependency for this library was just updated for this situation. https://github.com/github/fetch/pull/967

**Comment by abnemo** [comment] 2021-05-17 16:31
Any plans for the next release with updated dependencies?

**Comment by Nick-Mazuk** [comment] 2021-08-24 18:05
Running into this issue on Cloudflare Workers as well. Any dependency that uses cross-fetch cannot be used on Cloudflare Workers right now.

**Comment by ntinkler-calendly** [comment] 2022-02-08 16:02
Can confirm that I also see this issue when using packages that depend on cross-fetch in chrome-extension background scripts (Manifest v3, service worker based).

Cross-fetch blows up trying to use XHR to implement fetch when the environment provides fetch but not XHR.

Example error
```
"ReferenceError: XMLHttpRequest is not defined
    at chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/background.js:1716:23
    at new Promise (<anonymous>)
    at fetch (chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/background.js:1709:18)
```

**Comment by arun3528** [comment] 2022-02-18 19:09
Thanks a lot that worked for me as it a fresh project

**Comment by karol-cf** [comment] 2022-04-22 09:24
Hi,

I have this issue when trying to use Supabase in an MV3 Chrome Extension's service workers. I'm using an example I've found in [this YouTube video](https://www.youtube.com/watch?v=SP7eM_nXgJ4) (he's using MV2, which utilizes a background page, instead of service workers, so the issue is not present there). The extension allows you to sign up and log in with Supabase in a new Chrome tab. I've got a bundled version of supabase-js in my project. The supabase-js library is imported in the service worker and I create a client (as you can see on the screenshot below, I've tried binding the fetch as well). Whenever the user wants to authenticate, I send a message through the message passing API to my service worker and call various supabase.auth methods. Every time the signUp method is called, for example, I get "ReferenceError: XMLHttpRequest is not defined" and the method does not proceed further (on the third screenshot I've tried signing up and it threw an error).

![image](https://user-images.githubusercontent.com/90687732/164671121-7ad79d14-9391-4db5-b0fd-284d7b303a30.png)
![image (1)](https://user-images.githubusercontent.com/90687732/164671261-4ac1f4c1-650c-4b8c-b0c0-2465fd053f00.png)
![image (2)](https://user-images.githubusercontent.com/90687732/164671390-7c7af7c8-d02f-4980-a734-d3e2d1364343.png)

The only solution, that I think might work is removing the cross-fetch import from your lib and then bundling it, as mentioned above. Because of the MV3 requirements, I need that bundled js file anyway. However, I'd much rather not do that, because I don't think that this is a clean way of solving the problem. Any other ideas?

**Comment by dax70** [comment] 2023-01-17 03:57
Same issue with Cloudflare workers and noticed it's been open for 2+ years.

Any concerns in uncommenting line: 49?
https://github.com/lquixada/cross-fetch/blob/main/rollup.config.js#L49 
```
var ctx = global.fetch ? global : __self__;
```
I am using a package that uses `cross-fetch`.

**Comment by lquixada** [comment] 2023-06-09 22:27
I've been working on version 4 of `cross-fetch` to fix this issue. If anyone's interested, please run `npm install cross-fetch@latest-v4.x` in your project and give it a try. Let me know if any issues come up.

**Comment by lquixada** [comment] 2023-07-03 17:51
Version 4 has been officially released with the fix. Please check it out: `npm install cross-fetch`.

**Closed** 2023-07-08 18:41 UTC
Labels: worker
