### ISSUE TITLE
Types of property 'headers' are incompatible (with new 3.1.0)

### ISSUE THREAD

**Issue by Jauminha** [lquixada/cross-fetch#95] opened 2021-03-18 16:10 UTC
(First of all thanks for this amazing package!)

We are using cross-fetch to use the same client calls to our APIs from other APIs and any running application.
For our infrastructural needs, we created a small `customFetch` function on top of the `fetch` function so we could change the URL if a `cloud` parameter is passed or not:
```
export const customFetch = (input: RequestInfo, init: RequestInit, cloud?: CloudSubdomain | string): Promise<Response> => {
    let url = "";
    if (cloud) {
        url += createCloudUrl(cloud);
    }
    url += input;
    return fetch(url, init);
};
```

After updating to version 3.1.0 our code started to throw the following error:
```
Type 'Promise<import("/home/user/development/node_modules/cross-fetch/lib.fetch").Response>' is not assignable to type 'Promise<Response>'.
  Type 'import("/home/user/development/node_modules/cross-fetch/lib.fetch").Response' is not assignable to type 'Response'.
    Types of property 'headers' are incompatible.
      Type 'Headers' is missing the following properties from type 'Headers': [Symbol.iterator], entries, keys, values

22     return fetch(url, init);
```

I inspected the types from both `node_modules/typescript/lib/lib.dom.d.ts` and `node_modules/cross-fetch/lib.fetch.d.ts` and I see no difference apart from this:
```
declare var Headers: {
    prototype: Headers;
    new(init?: HeadersInit): Headers;
};
```

Hope you can shed some light on this.
Thanks for your time!

**Comment by jstewmon** [comment] 2021-03-18 19:36
The problem is that we're missing an augmentation from `lib.dom.iterable.d.ts`:

```ts
interface Headers {
    [Symbol.iterator](): IterableIterator<[string, string]>;
    /**
     * Returns an iterator allowing to go through all key/value pairs contained in this object.
     */
    entries(): IterableIterator<[string, string]>;
    /**
     * Returns an iterator allowing to go through all keys of the key/value pairs contained in this object.
     */
    keys(): IterableIterator<string>;
    /**
     * Returns an iterator allowing to go through all values of the key/value pairs contained in this object.
     */
    values(): IterableIterator<string>;
}
```

I think I can fix this by adding a graft for that specific interface and use declaration merging to get the right type definition in the cross-fetch index.d.ts.

**Comment by Jauminha** [comment] 2021-03-19 10:57
Awesome! Waiting for the merge 👍

**Comment by lquixada** [comment] 2021-03-19 23:14
Fix released on `3.1.2`. 👍  thanks everyone!

**Comment by ThomWright** [comment] 2021-03-22 12:08
@lquixada This is still happening for me on `3.1.2`.

**Comment by jstewmon** [comment] 2021-03-22 17:53
🤦  Sorry again - I was trying to quickly think of a way to fix this problem and I failed to really internalize the problem before proposing a solution.

I've got a new approach that I think will really work. I'll open a new PR shortly, including how I've tested it against the code sample in this issue.

**Comment by Jauminha** [comment] 2021-03-26 10:09
I guess the issue should be reopened until the fix has been merged? More people will stumble upon this

**Comment by lquixada** [comment] 2021-03-27 21:42
@Jauminha yeah, makes sense. I'm still working on this though!

**Comment by lquixada** [comment] 2021-03-28 02:10
@Jauminha jusr released an alpha version can you try your code with `npm install cross-fetch@3.1.3-alpha.4`

**Comment by iCrawl** [comment] 2021-03-28 16:41
This does not work at all now, because fetch is now a type only and cannot be used as a value/function anymore.

**Comment by lquixada** [comment] 2021-03-28 22:36
@iCrawl hi, can you try again with `npm install cross-fetch@3.1.3-alpha.6`?

**Comment by Jauminha** [comment] 2021-03-29 08:05
> This does not work at all now, because fetch is now a type only and cannot be used as a value/function anymore.
Yeahp, what iCrawl said.

**Comment by Jauminha** [comment] 2021-03-29 08:58
Sorry, email notifications went into spam.
Alpha.4 same as iCrawl.
Alpha.6 👍, works for me.

**Comment by jstewmon** [comment] 2021-03-29 12:37
@lquixada was there a problem with the `index.d.ts` from #100 you were trying to fix?

The changes you made put us nearly full circle where importing cross-fetch pollutes the globals with all the types that are in `lib.fetch.d.ts`. The folks using dom lib don't notice any problem b/c they already have all those types in their globals.

But, server app developers get incorrect type checking feedback. For example, this should not compile without using the dom lib, but it does because the compiler finds a global type definition for Request:

```ts
import fetch from "cross-fetch";

const req = new Request("http://example.com");
```

![image](https://user-images.githubusercontent.com/909418/112837515-9b7fbf00-9061-11eb-9466-9ddad0bb1637.png)

**Comment by lquixada** [comment] 2021-03-29 13:55
@jstewmon I feel the issue we're trying to address here is the conflict reported by @Jauminha regarding `Headers` (and any other fetch API member). So far `cross-fetch@3.1.3-alpha.6` seems to fix the problem.

Regarding the code you've mentioned, not sure why it should not compile. In Typescript, global types are a valid way to provide typing.

```javascript
import fetch from "cross-fetch";

const req = new Request("http://example.com");
```

The new `cross-fetch` version provides types from both imports and globals. The reason for this is that it can be used as a ponyfill (`import fetch from "cross-fetch"`) or as a polyfill (`import "cross-fetch/poyfill";`). PR #100 doesn't address the latter case.

That being said, I'm not saying that the current approach (`3.1.3-alpha.6`) should be the final one. We could certainly go back to discuss it but probably in another github issue or PR.

**Comment by jstewmon** [comment] 2021-03-29 14:10
> Regarding the code you've mentioned, not sure why it should not compile. In Typescript, global types are a valid way to provide typing.

In the example, I used `Request` as a `class` (concrete type), not an interface (abstract type), so the code will fail at runtime on the server. To be correct, it must be written as:

```
import fetch, { Request } from "cross-fetch";

const req = new Request("https://example.com");
```

> The reason for this is that it can be used as a ponyfill (`import fetch from "cross-fetch"`) or as a polyfill (`import "cross-fetch/poyfill";`). PR #100 doesn't address the latter case.

This requires separate type definition files. The global vars and types should be declared in `polyfill.d.ts`, which only needs the concrete declarations which are globally polyfilled and their supporting type declarations (no imports / exports are needed).

**Comment by lquixada** [comment] 2021-03-29 14:41
@jstewmon interesting approach! Do you feel we should open a new issue for that?

**Comment by jstewmon** [comment] 2021-03-29 14:54
I would say this has been a rather tricky issue to sort out, and this discussion has revealed much of the nuance in addressing it properly, so I lean towards keeping the details consolidated here. But, I don't think the choice has much consequence either way, so if you prefer a new issue, that's fine too.

**Comment by lquixada** [comment] 2021-03-30 18:40
thanks all! `3.1.3` has just been released 👍 

@jstewmon yeah I agree it's a tricky issue. I've released a new version so everyone gets the compilation error solved. Let's open a new issue/PR to address the global pollution and the polyfill case! Closing this one for now.

**Closed by lquixada** 2021-03-30 18:40 UTC
